import React, { useState, useEffect, useRef, useMemo } from 'react';

/**
 * Attempts to convert JSX syntax in code to React.createElement calls.
 * This is a best-effort transform for simple/moderate JSX patterns.
 */
function convertJSXToCreateElement(code) {
  // Strategy: Use regex-based recursive replacement for JSX tags.
  // This handles the most common patterns generated by LLMs.
  
  const MAX_ITERATIONS = 500;
  let iterations = 0;
  
  // First, convert JSX fragments <>...</> to React.createElement(React.Fragment, null, ...)
  code = code.replace(/<>([^]*?)<\/>/g, (_, children) => {
    return `React.createElement(React.Fragment, null, ${children.trim() || 'null'})`;
  });
  
  // Convert self-closing tags: <Tag prop="val" /> or <tag prop={expr} />
  // Process innermost self-closing tags first
  while (/<([a-zA-Z][a-zA-Z0-9.]*)\s*([^>]*?)\/>/s.test(code) && iterations < MAX_ITERATIONS) {
    iterations++;
    code = code.replace(/<([a-zA-Z][a-zA-Z0-9.]*)\s*([^>]*?)\/>/s, (_, tag, attrs) => {
      const propsStr = parseAttrsToProps(attrs.trim());
      const tagRef = /^[A-Z]/.test(tag) ? tag : `'${tag}'`;
      return `React.createElement(${tagRef}, ${propsStr})`;
    });
  }
  
  // Convert opening+closing tags: <Tag props>...children...</Tag>
  // Work from innermost outward
  iterations = 0;
  while (/<([a-zA-Z][a-zA-Z0-9.]*)\s*([^>]*)>([^<]*)<\/\1>/s.test(code) && iterations < MAX_ITERATIONS) {
    iterations++;
    code = code.replace(/<([a-zA-Z][a-zA-Z0-9.]*)\s*([^>]*)>([^<]*)<\/\1>/s, (_, tag, attrs, children) => {
      const propsStr = parseAttrsToProps(attrs.trim());
      const tagRef = /^[A-Z]/.test(tag) ? tag : `'${tag}'`;
      const childStr = children.trim();
      if (!childStr) {
        return `React.createElement(${tagRef}, ${propsStr})`;
      }
      // If children is plain text (not code), wrap in quotes; if it looks like an expression, leave it
      const childArg = /[{}]/.test(childStr) ? childStr : `"${childStr.replace(/"/g, '\\"')}"`;
      return `React.createElement(${tagRef}, ${propsStr}, ${childArg})`;
    });
  }
  
  // Handle tags with mixed children (already-converted createElement + text)
  iterations = 0;
  while (/<([a-zA-Z][a-zA-Z0-9.]*)\s*([^>]*)>([\s\S]*?)<\/\1>/s.test(code) && iterations < MAX_ITERATIONS) {
    iterations++;
    code = code.replace(/<([a-zA-Z][a-zA-Z0-9.]*)\s*([^>]*)>([\s\S]*?)<\/\1>/s, (_, tag, attrs, children) => {
      const propsStr = parseAttrsToProps(attrs.trim());
      const tagRef = /^[A-Z]/.test(tag) ? tag : `'${tag}'`;
      const childStr = children.trim();
      if (!childStr) {
        return `React.createElement(${tagRef}, ${propsStr})`;
      }
      return `React.createElement(${tagRef}, ${propsStr}, ${childStr})`;
    });
  }
  
  return code;
}

/**
 * Converts an HTML/JSX attribute string into a JS object string for React.createElement.
 */
function parseAttrsToProps(attrStr) {
  if (!attrStr) return 'null';
  
  const props = [];
  // Match: key={expression}, key="string", key='string', or boolean key
  const attrRegex = /(\w[\w-]*)(?:\s*=\s*(?:\{([^}]*(?:\{[^}]*\}[^}]*)*)\}|"([^"]*)"|'([^']*)'))?/g;
  let match;
  
  while ((match = attrRegex.exec(attrStr)) !== null) {
    let [, key, exprVal, dblVal, sglVal] = match;
    
    // Convert hyphenated attrs to camelCase (except data- and aria-)
    if (key.includes('-') && !key.startsWith('data-') && !key.startsWith('aria-')) {
      key = key.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
    }
    // className stays as-is, ref stays as-is
    
    if (exprVal !== undefined) {
      props.push(`${key}: ${exprVal}`);
    } else if (dblVal !== undefined) {
      props.push(`${key}: "${dblVal}"`);
    } else if (sglVal !== undefined) {
      props.push(`${key}: '${sglVal}'`);
    } else {
      // Boolean attribute
      props.push(`${key}: true`);
    }
  }
  
  if (props.length === 0) return 'null';
  return `{${props.join(', ')}}`;
}

/**
 * Validates that a code string can be parsed by attempting to create a Function.
 * Returns null if valid, or the error message if invalid.
 */
function validateSyntax(code) {
  try {
    new Function('React', `
      const { useState, useEffect, useRef, useCallback, useMemo, useReducer, useLayoutEffect, Fragment, createElement } = React;
      const h = React.createElement;
      ${code}
    `);
    return null;
  } catch (e) {
    return e.message;
  }
}

/**
 * Dynamically renders a game component from code string.
 * The code is compiled using new Function() and rendered as a React component.
 */
export default function GameRenderer({ gameCode, questions, onGameEnd, onAnswerResult }) {
  const [error, setError] = useState(null);
  const [GameComponent, setGameComponent] = useState(null);
  const keyRef = useRef(0);

  useEffect(() => {
    if (!gameCode) return;
    try {
      setError(null);
      keyRef.current += 1;
      
      let code = gameCode.trim();
      
      // Remove any markdown fences if present
      code = code.replace(/^```[\w]*\n?/, '').replace(/\n?```$/, '');

      // Strip export default if present
      code = code.replace(/export\s+default\s+/, '');
      
      // Attempt to convert JSX to React.createElement if JSX is detected
      const hasJSX = /return\s*\(?\s*<[a-zA-Z]/.test(code) || /<[a-zA-Z][^>]*>/.test(code);
      if (hasJSX) {
        const converted = convertJSXToCreateElement(code);
        // Only use converted code if it's valid JS; otherwise keep original
        const conversionError = validateSyntax(converted);
        if (!conversionError) {
          code = converted;
        } else {
          // Conversion broke the code. If original also has JSX, show error.
          const originalError = validateSyntax(code);
          if (originalError) {
            setError(`Game code has a syntax error: ${originalError}. Try regenerating the game or editing it to fix the issue.`);
            return;
          }
          // else: original code is valid (maybe false positive on JSX detection), use it
        }
      }
      
      // Final syntax check before execution
      const syntaxError = validateSyntax(code);
      if (syntaxError) {
        setError(`Game code has a syntax error: ${syntaxError}. Try regenerating the game or editing it to fix the issue.`);
        return;
      }
      
      // Create the component using Function constructor
      const createComponent = new Function(
        'React',
        `
        const { useState, useEffect, useRef, useCallback, useMemo, useReducer, useLayoutEffect, Fragment, createElement } = React;
        const h = React.createElement;
        
        ${code}
        
        // Try to find the exported component
        if (typeof GameComponent !== 'undefined') return GameComponent;
        if (typeof Game !== 'undefined') return Game;
        if (typeof MiniGame !== 'undefined') return MiniGame;
        
        throw new Error('Could not find game component. Make sure the function is named GameComponent.');
        `
      );
      
      const Comp = createComponent(React);
      setGameComponent(() => Comp);
    } catch (e) {
      console.error('Game render error:', e);
      setError(e.message);
    }
  }, [gameCode]);

  if (error) {
    return (
      <div className="flex items-center justify-center h-full bg-slate-900 text-white p-6">
        <div className="text-center max-w-md">
          <div className="text-4xl mb-4">⚠️</div>
          <h3 className="text-lg font-bold mb-2">Game Error</h3>
          <p className="text-sm text-slate-400 mb-4 whitespace-pre-wrap">{error}</p>
          <button
            onClick={() => onGameEnd?.({ score: 0, correctAnswers: 0, totalQuestions: 0, survivalTime: 0 })}
            className="px-4 py-2 bg-white/10 rounded-lg hover:bg-white/20 transition-colors"
          >
            Exit Game
          </button>
        </div>
      </div>
    );
  }

  if (!GameComponent) {
    return (
      <div className="flex items-center justify-center h-full bg-slate-900">
        <div className="animate-spin w-8 h-8 border-4 border-indigo-500 border-t-transparent rounded-full" />
      </div>
    );
  }

  return (
    <div style={{ width: '100%', height: '100%' }}>
      <ErrorBoundary key={keyRef.current} onError={(e) => setError(e)} onGameEnd={onGameEnd}>
        <GameComponent
          questions={questions || []}
          onGameEnd={onGameEnd || (() => {})}
          onAnswerResult={onAnswerResult || (() => {})}
        />
      </ErrorBoundary>
    </div>
  );
}

class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false, error: null };
  }

  static getDerivedStateFromError(error) {
    return { hasError: true, error: error.message };
  }

  componentDidCatch(error) {
    this.props.onError?.(error.message);
  }

  render() {
    if (this.state.hasError) {
      return (
        <div className="flex items-center justify-center h-full bg-slate-900 text-white p-6">
          <div className="text-center max-w-md">
            <div className="text-4xl mb-4">💥</div>
            <h3 className="text-lg font-bold mb-2">Game Crashed</h3>
            <p className="text-sm text-slate-400 mb-4">{this.state.error}</p>
            <button
              onClick={() => this.props.onGameEnd?.({ score: 0, correctAnswers: 0, totalQuestions: 0, survivalTime: 0 })}
              className="px-4 py-2 bg-white/10 rounded-lg hover:bg-white/20 transition-colors"
            >
              Exit Game
            </button>
          </div>
        </div>
      );
    }
    return this.props.children;
  }
}